services:
  mongo:
    image: mongo:latest
    container_name: nms_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: nms_rabbitmq
    ports:
      - "5672:5672" # RabbitMQ server
      - "15672:15672" # Management UI
  
  user-service:
    build: ./user-service
    container_name: nms_user-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  task-service:
    build: ./task-service
    container_name: nms_task-service
    ports:
      - "3002:3002"
    depends_on:
      - mongo
      - rabbitmq

  notification-service:
    build: ./notification-service
    container_name: nms_notification-service
    ports:
      - "3003:3003"
    depends_on:
      - rabbitmq
      - mongo

volumes:
  mongo-data: